/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as CamerasRouteImport } from './routes/cameras'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GisRouteImport } from './routes/gis'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as VehicleNumberRouteImport } from './routes/vehicle.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasRoute = CamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GisRoute = GisRouteImport.update({
  id: '/gis',
  path: '/gis',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleNumberRoute = VehicleNumberRouteImport.update({
  id: '/vehicle/$number',
  path: '/vehicle/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/cameras': typeof CamerasRoute
  '/dashboard': typeof DashboardRoute
  '/gis': typeof GisRoute
  '/registry': typeof RegistryRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/vehicle/$number': typeof VehicleNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/cameras': typeof CamerasRoute
  '/dashboard': typeof DashboardRoute
  '/gis': typeof GisRoute
  '/registry': typeof RegistryRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/vehicle/$number': typeof VehicleNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/cameras': typeof CamerasRoute
  '/dashboard': typeof DashboardRoute
  '/gis': typeof GisRoute
  '/registry': typeof RegistryRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/vehicle/$number': typeof VehicleNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/architecture'
    | '/cameras'
    | '/dashboard'
    | '/gis'
    | '/registry'
    | '/reports'
    | '/search'
    | '/settings'
    | '/watchlist'
    | '/vehicle/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/architecture'
    | '/cameras'
    | '/dashboard'
    | '/gis'
    | '/registry'
    | '/reports'
    | '/search'
    | '/settings'
    | '/watchlist'
    | '/vehicle/$number'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/architecture'
    | '/cameras'
    | '/dashboard'
    | '/gis'
    | '/registry'
    | '/reports'
    | '/search'
    | '/settings'
    | '/watchlist'
    | '/vehicle/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  CamerasRoute: typeof CamerasRoute
  DashboardRoute: typeof DashboardRoute
  GisRoute: typeof GisRoute
  RegistryRoute: typeof RegistryRoute
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  WatchlistRoute: typeof WatchlistRoute
  VehicleNumberRoute: typeof VehicleNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras': {
      id: '/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof CamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis': {
      id: '/gis'
      path: '/gis'
      fullPath: '/gis'
      preLoaderRoute: typeof GisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/$number': {
      id: '/vehicle/$number'
      path: '/vehicle/$number'
      fullPath: '/vehicle/$number'
      preLoaderRoute: typeof VehicleNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArchitectureRoute: ArchitectureRoute,
  CamerasRoute: CamerasRoute,
  DashboardRoute: DashboardRoute,
  GisRoute: GisRoute,
  RegistryRoute: RegistryRoute,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  WatchlistRoute: WatchlistRoute,
  VehicleNumberRoute: VehicleNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
